apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: helmproviderpr{{ .Values.prNumber }}
  # namespace: envpr{{ .Values.prNumber }}ns
spec:
  credentials:
    source: Secret
    secretRef:
      name: fmreal-kubeconfig
      namespace: envpr{{ .Values.prNumber }}ns
      key: kubeconfig