apiVersion: azure.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  name: azjetpr{{ .Values.prNumber }}
  # namespace: envpr{{ .Values.prNumber }}ns
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-creds
      key: creds
