apiVersion: dbforpostgresql.azure.jet.crossplane.io/v1alpha2
kind: Configuration
metadata:
  name: pgconfpr{{ .Values.prNumber }}
  # namespace: envpr{{ .Values.prNumber }}ns
spec:
  forProvider:
    name: array_nulls
    resourceGroupNameRef:
      name: envpr{{ .Values.prNumber }}rg
      # namespace: {{ .Values.providerNamespace }}
    serverNameRef:
      name: pgpr{{ .Values.prNumber }}
    value: "off"
  providerConfigRef:
    name: azjetpr{{ .Values.prNumber }}
    # namespace: {{ .Values.providerNamespace }}